# –ü—Ä–µ—Å–µ—Ç –¥–ª—è –∫–æ–Ω—Ñ–∏–≥—É—Ä–∞—Ü–∏–∏ —Å–µ—Ä–≤–µ—Ä–∞

[game]
hostname = "üïã PROJECT UTOPIA üïã‚úÖ[TTS][HRP]"
desc = "–ü–æ–≥—Ä—É–∑–∏—Ç–µ—Å—å –≤ –º—Ä–∞—á–Ω—É—é –∞–Ω—Ç–∏—É—Ç–æ–ø–∏—á–Ω—É—é –∞—Ç–º–æ—Å—Ñ–µ—Ä—É –ø—Ä–æ–µ–∫—Ç–∞ –£—Ç–æ–ø–∏–∏!.\nüîÆ –°–µ—Ä–≤–µ—Ä –æ—Å–Ω–æ–≤–∞–Ω –Ω–∞ —Å–±–æ—Ä–∫–µ WizardStation —Å –≤–Ω–µ—Å—ë–Ω–Ω—ã–º–∏ –º–æ–¥–∏—Ñ–∏–∫–∞—Ü–∏—è–º–∏ –∏ –¥–æ–ø–æ–ª–Ω–µ–Ω–∏—è–º–∏!\nüîÆ –ù–∞ —Å–µ—Ä–≤–µ—Ä–µ –ø—Ä–∏–≤–µ—Ç—Å—Ç–≤—É—é—Ç—Å—è –ø–æ–≤—ã—à–µ–Ω–Ω—ã–µ —Ç—Ä–µ–±–æ–≤–∞–Ω–∏—è –∫ RP.\nüîÆ –ò–º–µ–µ—Ç—Å—è —Å–≤–æ—è –ø–æ–¥–¥–µ—Ä–∂–∫–∞ TTS (Text-To-Speech).\nüí° –ü–æ–¥—Ä–æ–±–Ω–µ–µ –æ –ø—Ä–æ–µ–∫—Ç–µ —É–∑–Ω–∞–π—Ç–µ –≤ –Ω–∞—à–µ–º –¥–∏—Å–∫–æ—Ä–¥–µ!"
maxplayers = 50
soft_max_players = 30
lobbyenabled     = true
map_rotation = true

[infolinks]
bug_report = "https://discord.gg/HWwzygVsHA"
discord    = "https://discord.gg/WkQJYJ7Gvh"

[movement]
mob_pushing = false

[server]
rules_file = "StandardRuleset"
lobby_name = "Ô∏èüïã PROJECT UTOPIA üïã‚úÖ"

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_minutes = 0
deny_vpn = true
enable_without_admins = true
disable_with_admins = true

[admin]
see_own_notes = true
deadmin_on_join = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2
allow_multi_server_play = false

[vote]
restart_required_ratio = 0.7

[rules]
time = 180.0

[status]
enabled = true
bind = "38.180.111.229:1212"

[hub]
advertise = true
tags = "lang:ru,rp:high,region:ru_r,tts"